from pptx import Presentation
from openpyxl import Workbook
import logging

logger = logging.getLogger(__name__)


class DocArchitect:
    """Professional Document Generation for FRIDAY"""

    def create_ppt(self, topic, filename="FRIDAY_Presentation.pptx"):
        try:
            prs = Presentation()
            slide = prs.slides.add_slide(prs.slide_layouts[0])
            slide.shapes.title.text = f"Research on {topic}"
            slide.placeholders[1].text = "Generated by FRIDAY AI"
            prs.save(filename)
            return f"Professional PPT created: {filename}"
        except Exception as e:
            return f"PPT Error: {e}"

    def create_excel(self, data_dict, filename="FRIDAY_Data.xlsx"):
        try:
            wb = Workbook()
            ws = wb.active
            ws.title = "FRIDAY Report"
            # Simple data fill
            ws.append(["Category", "Value"])
            for k, v in data_dict.items():
                ws.append([k, v])
            wb.save(filename)
            return f"Excel sheet saved: {filename}"
        except Exception as e:
            return f"Excel Error: {e}"


def doc_update(command):
    da = DocArchitect()
    if "ppt" in command or "presentation" in command:
        topic = command.split("on")[-1].strip() if "on" in command else "General AI"
        return da.create_ppt(topic)
    if "excel" in command or "sheet" in command:
        return da.create_excel({"Example": 100, "Stat": 50})
    return "Document Architect online. Commands: create ppt, create excel."
