import datetime
import os

from jinja2 import Template

GENERATED_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "generated")

FLASK_TEMPLATE = Template("""from flask import Flask, jsonify, request

app = Flask(__name__)

{{ route_code }}

if __name__ == '__main__':
    app.run(debug=True)
""")

FLASK_ROUTE_TEMPLATE = Template("""@app.route('/{{ endpoint }}', methods=['{{ method }}'])
def {{ func_name }}():
    {{ logic }}
    return jsonify({{ result }})
""")

FASTAPI_TEMPLATE = Template("""from fastapi import FastAPI

app = FastAPI()

{{ route_code }}

if __name__ == '__main__':
    import uvicorn
    uvicorn.run(app, host='0.0.0.0', port=8000)
""")

REACT_COMPONENT = Template("""import React from 'react';

const {{ name }} = (props) => {
    return (
        <div className="{{ name.lower() }}">
            {{ content }}
        </div>
    );
};

export default {{ name }};
""")

SQLALCHEMY_MODEL = Template("""from sqlalchemy import Column, Integer, String, DateTime, Float
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class {{ class_name }}(Base):
    __tablename__ = '{{ table_name }}'

    {{ columns }}
""")


def _ensure_generated_dir():
    os.makedirs(GENERATED_DIR, exist_ok=True)


def _timestamp():
    return datetime.datetime.now().strftime("%Y%m%d_%H%M%S")


def _try_llm(description: str, language: str) -> str | None:
    try:
        from modules.llm.openrouter_client import ask_llm

        prompt = (
            f"Generate {language} code only (no explanation). "
            f"Description: {description}"
        )
        return ask_llm(prompt)
    except Exception:
        return None


def generate_code(description: str, language: str = "python") -> str:
    _ensure_generated_dir()

    try:
        code = _try_llm(description, language)
        if code:
            ext = _extension(language)
            fname = f"generated_{_timestamp()}{ext}"
            fpath = os.path.join(GENERATED_DIR, fname)
            with open(fpath, "w") as f:
                f.write(code)
            return f"Code generated via LLM -> {fpath}"
    except Exception:
        pass

    # Fallback: template-based
    if language == "flask":
        code = FLASK_TEMPLATE.render(
            route_code=f"@app.route('/')\ndef index():\n    return jsonify({{'message': '{description}'}})",
        )
        fname = f"flask_app_{_timestamp()}.py"
    elif language == "fastapi":
        code = FASTAPI_TEMPLATE.render(
            route_code=f"@app.get('/')\nasync def root():\n    return {{'message': '{description}'}}",
        )
        fname = f"fastapi_app_{_timestamp()}.py"
    elif language == "react":
        code = REACT_COMPONENT.render(
            name="GeneratedComponent", content="{/* " + description + " */}"
        )
        fname = f"GeneratedComponent_{_timestamp()}.jsx"
    elif language == "sqlalchemy":
        code = SQLALCHEMY_MODEL.render(
            class_name="GeneratedModel",
            table_name="generated",
            columns="id = Column(Integer, primary_key=True)\n    name = Column(String)",
        )
        fname = f"model_{_timestamp()}.py"
    else:
        code = f"# {description}\n# Generated by FRIDAY Devops Compiler\nprint('{description}')\n"
        fname = f"script_{_timestamp()}.py"

    fpath = os.path.join(GENERATED_DIR, fname)
    with open(fpath, "w") as f:
        f.write(code)
    return f"Generated template code -> {fpath}"


def _extension(language: str) -> str:
    lang_map = {
        "python": ".py",
        "flask": ".py",
        "fastapi": ".py",
        "sqlalchemy": ".py",
        "react": ".jsx",
        "javascript": ".js",
        "typescript": ".ts",
        "go": ".go",
        "rust": ".rs",
        "html": ".html",
        "css": ".css",
    }
    return lang_map.get(language.lower(), ".txt")
